### ISSUE TITLE
Problem with accents in Spanish OSPAN

### ISSUE THREAD

**Issue by iriadf** [tmalsburg/py-span-task#12]
Dear Titus, 
First of all, thank you for this useful contribution! 

I've been trying to run the Spanish version of the OSPAN task and every time I hit the accent key there's an error and Python closes. Below is the error that appears on my terminal. 
I had saved the files as UTF-8 but the error persists. Otherwise, the script works perfectly. Any hints on how to solve this? 

I apologize in advance for my programming clumsiness. 
Best!
IDF

2017-08-22 17:31:44.276 Python[4237:364490] An uncaught exception was raised
2017-08-22 17:31:44.276 Python[4237:364490] -[__NSCFConstantString characterAtIndex:]: Range or index out of bounds
2017-08-22 17:31:44.277 Python[4237:364490] (
	0   CoreFoundation                      0x00007fff88d2303c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9006f76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff88d22eed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff88bf5ed6 -[__NSCFString characterAtIndex:] + 102
	4   Tk                                  0x000000010233f5a8 TkpInitKeymapInfo + 751
	5   Tk                                  0x000000010234560b Tk_MacOSXSetupTkNotifier + 880
	6   Tcl                                 0x000000010221a49c Tcl_DoOneEvent + 316
	7   _tkinter.so                         0x000000010219032f Tkapp_MainLoop + 415
	8   Python                              0x00000001000c6d4c PyEval_EvalFrameEx + 33852
	9   Python                              0x00000001000ca193 PyEval_EvalCodeEx + 2115
	10  Python                              0x00000001000c6ae5 PyEval_EvalFrameEx + 33237
	11  Python                              0x00000001000ca193 PyEval_EvalCodeEx + 2115
	12  Python                              0x00000001000ca2b6 PyEval_EvalCode + 54
	13  Python                              0x00000001000ef21e PyRun_FileExFlags + 174
	14  Python                              0x00000001000ef4ba PyRun_SimpleFileExFlags + 458
	15  Python                              0x00000001001066dd Py_Main + 3101
	16  Python                              0x0000000100000f14 Python + 3860
)
2017-08-22 17:31:44.278 Python[4237:364490] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFConstantString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff88d2303c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9006f76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff88d22eed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff88bf5ed6 -[__NSCFString characterAtIndex:] + 102
	4   Tk                                  0x000000010233f5a8 TkpInitKeymapInfo + 751
	5   Tk                                  0x000000010234560b Tk_MacOSXSetupTkNotifier + 880
	6   Tcl                                 0x000000010221a49c Tcl_DoOneEvent + 316
	7   _tkinter.so                         0x000000010219032f Tkapp_MainLoop + 415
	8   Python                              0x00000001000c6d4c PyEval_EvalFrameEx + 33852
	9   Python                              0x00000001000ca193 PyEval_EvalCodeEx + 2115
	10  Python                              0x00000001000c6ae5 PyEval_EvalFrameEx + 33237
	11  Python                              0x00000001000ca193 PyEval_EvalCodeEx + 2115
	12  Python                              0x00000001000ca2b6 PyEval_EvalCode + 54
	13  Python                              0x00000001000ef21e PyRun_FileExFlags + 174
	14  Python                              0x00000001000ef4ba PyRun_SimpleFileExFlags + 458
	15  Python                              0x00000001001066dd Py_Main + 3101
	16  Python                              0x0000000100000f14 Python + 3860
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
MacBook-Pro-de-Iria:SpanishOperationSpan iriadediosflores$

**Comment by tmalsburg** [comment]
Hi @iriadf, I can't replicate this issue on my system (Ubuntu Linux) and the error looks as if it was caused by one of the libraries that are part of Python and not by my code.  When you google `libc++abi.dylib: terminating with uncaught exception of type NSException`, you find that many other people also experience this issue in other contexts. I would try updating Python. Let me know if that doesn't fix it.
