### ISSUE TITLE
GermanReadingSpan configuration

### ISSUE THREAD

**Issue by sebsau** [tmalsburg/py-span-task#16]
The instructions in the configuration file for the German reading span task are a bit unidiomatic in some places, really minor things. I made an attempt of improving them and maybe that is helpful.

[configuration_updated_instructions.py.txt](https://github.com/tmalsburg/py-span-task/files/6601053/configuration_updated_instructions.py.txt)

**Comment by tmalsburg** [comment]
Thank you!
