### ISSUE TITLE
Interface does not react (German Reading Span)

### ISSUE THREAD

**Issue by sebsau** [tmalsburg/py-span-task#17]
On Mac OS Big Sur 11.4, I can start the task and the window with the instructions appears. I can't, however, not interact with that window (can't click in it, doesn't accept space bar or any other key presses). I've tried on Windows 10 and there it worked fine. Both computers ran Python 3.9. Any idea what the reason for this could be?

**Comment by tmalsburg** [comment]
Sorry to hear. Unfortunately, I don't have access to a Mac OS system and can't test this myself.  py-span-task is a pretty straightforward tkinter application, so I suspect that the root of the issue lies on the Python side.

**Comment by sebsau** [comment]
The "solution" was that I used a Windows computer at the end, there it works just fine.

**Comment by tmalsburg** [comment]
Thanks for the update. Glad you could solve it.
