### ISSUE TITLE
order of instructions for German span task

### ISSUE THREAD

**Issue by yanakpv** [tmalsburg/py-span-task#18]
Instructions for the German span task appear to be coming in a slightly wrong order: currently, participants are receiving instructions for the practice memory task after that task is over (instructions3), and are not receiving the instructions telling them that the familiarisation period is over. 

It works fine if instructions are rearranged as follows:

```
  main_frame = MainFrame(root,
                         Text(welcome_text, CENTER),
                         Text(instructions1), Text(instructions2),
                         PracticeProcessingItemsScript(processing_items),
                         Text(instructions3),
                         TestScript(processing_items, target_items,
                                    practice_levels, practice_items_per_level,
                                    "practice"),
                         Text(instructions4),
                         TestScript(processing_items, target_items, levels,
                                    items_per_level, "test"),
                         GoodbyeScript())
```
Was:

```
  main_frame = MainFrame(root,
                         Text(welcome_text, CENTER),
                         Text(instructions1),
                         PracticeProcessingItemsScript(processing_items),
                         Text(instructions2),
                         TestScript(processing_items, target_items,
                                    practice_levels, practice_items_per_level,
                                    "practice"),
                         Text(instructions3),
                         TestScript(processing_items, target_items, levels,
                                    items_per_level, "test"),
                         GoodbyeScript())

``` 

Instructions 1 & 2 could be merged together, and instr. 3 and 4 renamed 2 and 3 respectively, then the span tasks in other languages shouldn't be affected, as far as I can tell. 

There is also confusion among quite a lot of participants whether they should be continuing reading the sentences aloud after the first practice block. I've added a line explaining that they should continue doing so to instructions 3 and 4.

**Comment by tmalsburg** [comment]
I checked: The German operation span task looks okay, but the instructions for the German reading span task are indeed in the wrong order.  The solution is to rewrite the instructions in the file `configuration.py`.  (We can't change the order in `pyspantask.py` because then all the order in all the other tasks would be incorrect.)  Would you like to fix the configuration?  If yes, I could then incorporate your corrections into this repository.

**Comment by yanakpv** [comment]
Yes, I meant the reading span task of course, sorry! Happy to submit a fix

**Comment by tmalsburg** [comment]
I've already fixed it.  Could you please check?

**Comment by tmalsburg** [comment]
The issue was that the instructions were numbered incorrectly.  Former `instructions3` should have been `instructions2` and former `instructions4` should have been `instructions3`.

**Comment by tmalsburg** [comment]
I also fixed a bug where the prompt for a subject ID wasn't shown.

**Comment by tmalsburg** [comment]
I've read through some of the stimuli of the German reading span task and must say that some of them are a bit cruel and disturbing. Personally, I'd replace those.  If you decide to replace them, please consider sharing your improved stimuli. :)

**Comment by yanakpv** [comment]
Ah, I was too slow! :) Looks good now, thanks! I'd just add "Bitte denken Sie daran, die Sätze laut vorzulesen." as the last sentence on every instruction page, participants are often confused whether this is something they should be doing throughout the experiment.

**Comment by tmalsburg** [comment]
>  I'd just add "Bitte denken Sie daran, die Sätze laut vorzulesen."

Ah, right, good point.  Just added it.  Thank you!
