### ISSUE TITLE
Typo in German sentences?

### ISSUE THREAD

**Issue by sebsau** [tmalsburg/py-span-task#19]
The sentence on line 72 of the German reading span task reads "Weil sie die die beste Ausbildung genoss, kommt ihre Dattelpalme nicht von ungefähr." (with "die die"). Is this a typo or intentional?

**Comment by tmalsburg** [comment]
Typo, I guess.  Thanks.

**Comment by tmalsburg** [comment]
I should note that these German stimuli were not actually used in an experiment yet (not to my knowledge). They're probably not super polished for that reasons and it's good that you're having a close look at them.
