### ISSUE TITLE
Typos in German sentence (that should be correct)

### ISSUE THREAD

**Issue by sebsau** [tmalsburg/py-span-task#20]
This sentence in the German version has a typo (marked in bold), but should be correct:

- Am Vormittag sind die Täter ins Haus eingedrungen **sein** und haben den Mann überwältigt.

**Comment by tmalsburg** [comment]
Thank you. Fixed.  I haven't developed or used the materials for the German reading span task myself and therefore can't vouch for them. Please check carefully (if you haven't done that yet) before testing participants.
